### ISSUE TITLE
Add a loading/processing screen

### ISSUE THREAD

**Issue by afeedhshaji** [abinpaul1/youtube-mp3-dl-mp3juice#2]
When a user clicks the download button, the browser navigates to a link: `https://audio.kenobi.win/api/youtube-dl/download?ybid=<>`. For longer videos, it takes a long time before we get navigated back to the home screen. At first, I thought there was some issue with the website. Perhaps a loading screen or a processing screen (maybe with a progress bar?) to let users know that the requested resource is being prepared would be helpful. Overall, the UI looks very minimal and easy to use! 👍

**Comment by abinpaul1** [comment]
Added in https://github.com/abinpaul1/youtube-mp3-dl-mp3juice/commit/7841330720259afdecbabd9f4477f06c0036e7cb
